name: news
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
   #* StateManagement Package
  provider: ^6.0.3
  #* Internet Connection Control Package
  connectivity_plus: ^2.3.7
  #* Svg Package
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  timeago: ^3.3.0
  flutter_custom_tabs: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.5
  blurrycontainer: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/


